AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  IPOListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: src/listing/
      Handler: main.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          SENDGRID_API_KEY: '{{resolve:secretsmanager:SENDGRID_API_KEY}}'
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Enabled: True 