AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  IPOListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      CodeUri: src/listing/
      Handler: main.lambda_handler
      Runtime: python3.8
      Policies:
        - SESCrudPolicy:
            IdentityName: '*'
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Enabled: True 