AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  IPOListingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      Handler: main.lambda_handler
      Runtime: python3.8
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(5 * * * ? *)
            Enabled: True 